version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/docqa?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Vipin@123
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=docqa
      - MYSQL_ROOT_PASSWORD=Vipin@123
    ports:
      - "3306:3306"