version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: docqa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - docqa-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - docqa-network
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - docqa-network
networks:
  docqa-network:
    driver: bridge